a=int(input("Enter a value:"))
print("the value your entered:", a,"type:", type(a))
b=input("Enter a value:")
print("the value your entered:{} and type:{}".format(b,type(b)))
c=input("Enter a value:")
print("the value your entered:", c, "type:", type(c))
d=input("Enter a value:")
print("the value your entered:{} and type:{}".format(d,type(d)))
e=int(input("Enter a value:"))
print("the value your entered:", e,"type:", type(e))

